var tableauQuestion = [
    {   question : "Care este maximul de alcolemie permis in sange pentru a conduce ?",
        propositionA : "0.05%(F)",
        propositionB : "0.08%(A)",
        propositionC : "0.13%(F)",
        propositionD : "0.01%(F)",
        reponse : "B"},
		
    {   question : "Care este limita maxima de viteza in localitati ?",
        propositionA : "70 km/h(F)",
        propositionB : "60 km/h(F)",
        propositionC : "50 km/h(A)",
        propositionD : "110 km/h(F)",
        reponse : "C"},
		
    {   question : "Daca semaforul arata culoarea rosie ce trebuie sa faceti ?",
        propositionA : "Sa bag viteza(F)",
        propositionB : "Sa incetinesc(F)",
        propositionC : "Sa opresc pana se face verde(A)",
        propositionD : "Sa stau pe telefon(F)",
        reponse : "C"},
	
	{   question : "Daca o ambulanta vine cu sirenele pornite, ce trebuie sa faci ?",
        propositionA : "Sa bag viteza(F)",
        propositionB : "Sa ma opresc si sa o filmez(F)",
        propositionC : "Sa trag pe dreapta sa ii dau voie sa treaca(A)",
        propositionD : "Sa stau pe telefon(F)",
        reponse : "C"},
		
	{   question : "Daca un ofiter de la circulatie va pune sa trageti pe dreapta, ce faceti?",
        propositionA : "Trag pe dreapta(A)",
        propositionB : "Bag viteza(F)",
        propositionC : "O injur(F)",
        propositionD : "Incep sa rad(F)",
        reponse : "A"},
		
	{   question : "Daca vezi pe cineva care nu respecta regulamentul rutier, ce faceti ?",
        propositionA : "Sa anunt politia(A)",
        propositionB : "Sa o folosesc(F)",
        propositionC : "Sa o arunc(F)",
        propositionD : "Sa omor pe cineva cu ea(F)",
        reponse : "A"},
	
	{   question : "Ce se intampla daca furati o masina?",
        propositionA : "O vand si scot multi bani(F)",
        propositionB : "O sa fiu prins de politie si pus la socoteala(A)",
        propositionC : "O arunc in apa(F)",
        propositionD : "O fac bucati(F)",
        reponse : "B"},
		
	{   question : "Condusul fara permis cu ce se pedepseste ?",
        propositionA : "Avertizare(F)",
        propositionB : "Inchisoare(A)",
        propositionC : "Aruncare la gunoi(F)",
        propositionD : "Amenda de 500.000$(F)",
        reponse : "B"},
		
	{   question : "Daca faceti curse ilegale, cu ce se pedepsesc ?",
        propositionA : "Inchisoare si amenda(A)",
        propositionB : "Luarea masini pe sus(F)",
        propositionC : "Spargerea acesteia(F)",
        propositionD : "Ii se da foc(F)",
        reponse : "A"},
		
	{   question : "Puteti schimba pozitia autovehiculului, daca acesta a fost implicat intr-un accident din care a rezultat moartea sau vatamarea integritatii corporale ori a sanatatii unor persoane?",
        propositionA : "da, cu incuviintarea politiei, care cerceteaza accidentul(A)",
        propositionB : "da, daca persoana vatamata se poate deplasa singura(F)",
        propositionC : "nu, pana la sosirea ambulantei(F)",
        propositionD : "nu, pana nu fac o poza pentru facebook(F)",
        reponse : "A"},
]
